# Generated by Django 5.2.3 on 2025-07-06 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_financialaccount_financialreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=1)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], default='pending', max_length=10)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('receipt_number', models.CharField(blank=True, max_length=50)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_aids', to=settings.AUTH_USER_MODEL)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_aids', to='base.beneficiary')),
            ],
            options={
                'verbose_name_plural': 'Financial Aids',
                'ordering': ['-request_date'],
            },
        ),
        migrations.RemoveField(
            model_name='budget',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='transactions',
        ),
        migrations.DeleteModel(
            name='FinancialAccount',
        ),
        migrations.RemoveField(
            model_name='financialreport',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='financialtransaction',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='financialtransaction',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='financialtransaction',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='financialtransaction',
            name='sponsor',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='FinancialReport',
        ),
        migrations.DeleteModel(
            name='FinancialTransaction',
        ),
    ]
