# Generated by Django 5.2.3 on 2025-07-06 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_financialaid_remove_budget_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('level', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('college', 'College'), ('university', 'University')], max_length=20)),
                ('is_core', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('term', 'Term Report'), ('annual', 'Annual Report'), ('subject', 'Subject Analysis'), ('comparative', 'Comparative Analysis')], max_length=20)),
                ('academic_year', models.CharField(max_length=10)),
                ('term', models.CharField(blank=True, max_length=20, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='performance_reports/')),
                ('notes', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=10)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(max_length=2)),
                ('comments', models.TextField(blank=True)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_performances', to='base.beneficiary')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subject')),
            ],
            options={
                'ordering': ['academic_year', 'term', 'subject__name'],
                'unique_together': {('beneficiary', 'subject', 'term', 'academic_year')},
            },
        ),
    ]
