# Generated by Django 5.2.3 on 2025-07-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_subject_performancereport_subjectperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicperformance',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='performance_reports/'),
        ),
    ]
