# Generated by Django 5.2.3 on 2025-09-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_communicationcategory_announcement_discussionthread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='admission_letter',
            field=models.FileField(blank=True, null=True, upload_to='beneficiary_docs/admission_letters/'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='current_school',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='fee_statement',
            field=models.FileField(blank=True, null=True, upload_to='beneficiary_docs/fee_statements/'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='fee_structure',
            field=models.FileField(blank=True, null=True, upload_to='beneficiary_docs/fee_structures/'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='guardian_full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='guardian_id_copy',
            field=models.FileField(blank=True, null=True, upload_to='beneficiary_docs/guardian_ids/'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='guardian_type',
            field=models.CharField(blank=True, choices=[('single_parent', 'Single Parent'), ('both_parents', 'Both Parents'), ('guardian', 'Guardian')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='letters',
            field=models.FileField(blank=True, null=True, upload_to='beneficiary_docs/letters/'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='previous_school',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='receipts',
            field=models.FileField(blank=True, null=True, upload_to='beneficiary_docs/receipts/'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='referral_source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='residence_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='residence_directions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
